name: Update Packagist

on:
  release:
    types: [created]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Update Packagist
        uses: pxgamer/packagist-update-action@v1
        with:
          username: ${{ secrets.PACKAGIST_USERNAME }}
          api_token: ${{ secrets.PACKAGIST_API_TOKEN }}